### ISSUE TITLE
Exception on adding readObject / writeObject methods with Javadoc

### ISSUE THREAD

**Issue by trespasserw** [stephenc/intellij-generate-serialization-helpers#1]
The exception below is caused by a leading whitespace passed into `PsiElementFactory.createMethodFromText()`:

```
Incorrect method ' /**
 * Called when object is to be deserialized from a stream.
 *
 * @param stream the stream to read the object from.
 * @throws java.io.IOException    if the object could not be read.
 * @throws java.lang.ClassNotFoundException if a class required to read the object could not be found.
 * @see <a href="http://download.oracle.com/javase/1.3/docs/guide/serialization/spec/input.doc4.html">The Java
 *      Object Serialization Specification</a>
 */
private void readObject(java.io.ObjectInputStream stream) throws java.lang.ClassNotFoundException, java.io.IOException { stream.defaultReadObject();}'
com.intellij.util.IncorrectOperationException: Incorrect method ' /**
 * Called when object is to be deserialized from a stream.
 *
 * @param stream the stream to read the object from.
 * @throws java.io.IOException    if the object could not be read.
 * @throws java.lang.ClassNotFoundException if a class required to read the object could not be found.
 * @see <a href="http://download.oracle.com/javase/1.3/docs/guide/serialization/spec/input.doc4.html">The Java
 *      Object Serialization Specification</a>
 */
private void readObject(java.io.ObjectInputStream stream) throws java.lang.ClassNotFoundException, java.io.IOException { stream.defaultReadObject();}'
 at com.intellij.psi.impl.PsiJavaParserFacadeImpl.newException(PsiJavaParserFacadeImpl.java:416)
 at com.intellij.psi.impl.PsiJavaParserFacadeImpl.createMethodFromText(PsiJavaParserFacadeImpl.java:227)
 at com.intellij.psi.impl.PsiElementFactoryImpl.createMethodFromText(PsiElementFactoryImpl.java:752)
 at com.intellij.psi.impl.PsiJavaParserFacadeImpl.createMethodFromText(PsiJavaParserFacadeImpl.java:236)
 at com.github.stephenc.intellij.plugin.generateserializationhelpers.GenerateReadObjectHandler.createMethod(GenerateReadObjectHandler.java:55)
 at com.github.stephenc.intellij.plugin.generateserializationhelpers.GenerateMethodHandler.generateMemberPrototypes(GenerateMethodHandler.java:78)
 at com.intellij.codeInsight.generation.GenerateMembersHandlerBase.doGenerate(GenerateMembersHandlerBase.java:135)
 at com.intellij.codeInsight.generation.GenerateMembersHandlerBase.lambda$invoke$1(GenerateMembersHandlerBase.java:90)
 at com.intellij.openapi.command.WriteCommandAction$4.run(WriteCommandAction.java:185)
 at com.intellij.openapi.command.WriteCommandAction$Simple.run(WriteCommandAction.java:167)
 at com.intellij.openapi.application.RunResult.run(RunResult.java:35)
 at com.intellij.openapi.command.WriteCommandAction$2.run(WriteCommandAction.java:113)
 at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:122)
 at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:100)
 at com.intellij.openapi.command.WriteCommandAction.performWriteCommandAction(WriteCommandAction.java:108)
 at com.intellij.openapi.command.WriteCommandAction.execute(WriteCommandAction.java:83)
 at com.intellij.openapi.command.WriteCommandAction.runWriteCommandAction(WriteCommandAction.java:187)
 at com.intellij.openapi.command.WriteCommandAction.runWriteCommandAction(WriteCommandAction.java:174)
 at com.intellij.codeInsight.generation.GenerateMembersHandlerBase.invoke(GenerateMembersHandlerBase.java:87)
 at com.intellij.codeInsight.actions.CodeInsightAction.lambda$null$0(CodeInsightAction.java:59)
 at com.intellij.codeInsight.actions.CodeInsightAction.lambda$actionPerformedImpl$1(CodeInsightAction.java:65)
 at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:129)
 at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:100)
 at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:86)
 at com.intellij.codeInsight.actions.CodeInsightAction.actionPerformedImpl(CodeInsightAction.java:55)
 at com.intellij.codeInsight.actions.CodeInsightAction.actionPerformed(CodeInsightAction.java:41)
 at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:197)
 at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
 at com.intellij.openapi.application.TransactionGuardImpl.submitTransactionAndWait(TransactionGuardImpl.java:156)
 at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:211)
 at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep.performAction(PopupFactoryImpl.java:875)
 at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep.lambda$onChosen$0(PopupFactoryImpl.java:863)
 at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:199)
 at com.intellij.ui.popup.AbstractPopup.lambda$null$7(AbstractPopup.java:1390)
 at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
 at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
 at java.awt.EventQueue.access$500(EventQueue.java:97)
 at java.awt.EventQueue$3.run(EventQueue.java:709)
 at java.awt.EventQueue$3.run(EventQueue.java:703)
 at java.security.AccessController.doPrivileged(Native Method)
 at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
 at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
 at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:863)
 at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:699)
 at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:385)
 at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
 at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
 at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
 at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
 at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

Original issue: https://youtrack.jetbrains.com/issue/IDEA-160404

**Comment by stephenc** [comment]
Fixed in 1.0.6
